name: Drupal CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image 
        run: docker-compose up -d --build   

      - name: Wait for Drupal to be ready
        run: |
          for i in {1..60}; do
            if curl -s localhost:8080 | grep -q "Drupal"; then
              echo "Drupal is ready!"
              break
            else
              echo "Waiting for Drupal..."
              sleep 1
            fi
          done

      - name: Install Dependencies (if needed)
        run: docker-compose exec drupal-web composer install # If you need to run Composer

      - name: Prepare environment for PHPUnit
        run: |
          docker-compose exec drupal-web chmod +x ./vendor/bin/phpunit # Make PHPUnit executable
          docker-compose exec drupal-web chown -R www-data:www-data sites/default/files/ # Set file permissions

      - name: Run Drupal Tests (PHPUnit)
        run: docker-compose exec drupal-web ./vendor/bin/phpunit -c core --testsuite unit

