name: Drupal Informational Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker-compose up -d --build

      - name: Wait for Drupal to be ready
        run: |
          for i in {1..60}; do
            if curl -s localhost:8080 | grep -q "Drupal"; then
              echo "Drupal is ready!"
              break
            else
              echo "Waiting for Drupal..."
              sleep 1
            fi
          done

      - name: Display Drupal status (or any other information)
        run: docker-compose exec drupal-web drush status -y

      - name: Always succeed
        run: echo "This job will always succeed"

